services:
  mc-java:
    image: itzg/minecraft-server:latest
    container_name: mc-java
    ports:
      - "25575:25575"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      MEMORY: "10000M"
      SERVER_PORT: "25575" # Tells the Minecraft server to bind to 25575
      MOTD: "Server 3: Kinetic Jubilee"
      ONLINE_MODE: "false"
      ENABLE_COMMAND_BLOCK: "true"
      SEED: "-9079713339616171283"
      MAX_TICK_TIME: "-1"
      OPS: "${SERVER_OP}"
      MODRINTH_PROJECTS: |-
        fabric-api
        worldedit
        ferrite-core
        lithium
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      ENFORCE_SECURE_PROFILE: "false"
      LOG_IPS: "false"
    volumes:
      - "./mc_data:/data"
    deploy:
      resources:
        limits:
          memory: 12G

  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.17
    container_name: playit-agent
    network_mode: host
    environment:
      - SECRET_KEY=${PLAYIT_SECRET}
