services:
  mc-java:
    image: itzg/minecraft-server:latest
    container_name: mc-java
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    environment:
      UID: 1000
      PUID: "1000"
      PGID: "1000"
      EULA: "TRUE"
      TYPE: "FABRIC"
      MEMORY: "10000M"
      SERVER_PORT: "25565" # Tells the Minecraft server to bind to 25575
      MOTD: "Server 3: Kinetic Jubilee"
      ONLINE_MODE: "false"
      ENABLE_COMMAND_BLOCK: "true"
      SEED: "-9079713339616171283"
      MAX_TICK_TIME: "-1"
      OPS: "${SERVER_OP}"
      OP_PERMISSION_LEVEL: "4"
      SPAWN_PROTECTION: "0"
      MODE: "1"
      FORCE_GAMEMODE: "true"
      ENFORCE_SECURE_PROFILE: "false"
      LOG_IPS: "false"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_PASSWD}"
      RCON_PORT: 25575
      RCON_CMDS_STARTUP:  |-
        op ${SERVER_OP}
        op SairajBinAhmed
        say hello world
        carpet scripts_optimization true
        carpet lagFreeSpawning true
        
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_ALLOWED_VERSION_TYPE: "alpha"
      MODRINTH_PROJECTS: |-
        fabric-api
        no-chat-reports
        lithium
        ferrite-core
        krypton
        debugify
        distanthorizons
        c2me-fabric
        worldedit
        carpet
    volumes:
      - "./mc_data:/data"
    deploy:
      resources:
        limits:
          memory: 12G
  
  restore-backup:
    image: itzg/mc-backup
    restart: "no"
    entrypoint: restore-tar-backup
    volumes:
      - ./mc_data:/data
      - ./mc_backups:/backups:ro
  backup-mc:
    image: itzg/mc-backup
    depends_on:
      mc-java:
        condition: service_healthy
    environment:
      UID: 1000
      PUID: "1000"
      PGID: "1000"
      BACKUP_INTERVAL: "5m"
      RCON_HOST: mc-java
      INITIAL_DELAY: 0
      TAR_COMPRESS_METHOD: lzma
      PRE_BACKUP_SCRIPT: |
        echo "Before backup!"
        ls -l /config/rclone/rclone.conf
        cat /config/rclone/rclone.conf | grep "\["
        rclone config paths
        rclone copy foo_inf:mc_backups/ ./mc_backups/
        echo "Also before backup from $$RCON_HOST to $$DEST_DIR"
      POST_BACKUP_SCRIPT: |
        rclone copy ./mc_backups/ foo_inf:mc_backups/
        echo "Backup to rclone remote complete"
    volumes:
      - ./rclone.conf:/config/rclone/rclone.conf:ro
      - ./mc_data:/data:ro
      - ./mc_backups:/backups

  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.17
    container_name: playit-agent
    network_mode: host
    environment:
      - SECRET_KEY=${PLAYIT_SECRET}
