services:
  mc-java:
    image: itzg/minecraft-server:latest
    container_name: mc-java
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      MEMORY: "10000M"
      SERVER_PORT: "25565" # Tells the Minecraft server to bind to 25575
      MOTD: "Server 3: Kinetic Jubilee"
      ONLINE_MODE: "true"
      ENABLE_COMMAND_BLOCK: "true"
      SEED: "-9079713339616171283"
      MAX_TICK_TIME: "-1"
      OPS: "${SERVER_OP}"
      OP_PERMISSION_LEVEL: "4"
      SPAWN_PROTECTION: "0"
      FORCE_GAMEMODE: "false"
      ENFORCE_SECURE_PROFILE: "false"
      LOG_IPS: "false"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "${RCON_PASSWD}"
      RCON_PORT: 25575
      RCON_CMDS_STARTUP:  |-
        op ${SERVER_OP}
        say hello world
        carpet scripts_optimization true
        carpet lagFreeSpawning true
        
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_ALLOWED_VERSION_TYPE: "alpha"
      MODRINTH_PROJECTS: |-
        fabric-api
        no-chat-reports
        lithium
        ferrite-core
        krypton
        debugify
        distanthorizons
        c2me-fabric
        worldedit
        carpet
    volumes:
      - "./mc_data:/data"
    deploy:
      resources:
        limits:
          memory: 12G

  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.17
    container_name: playit-agent
    network_mode: host
    environment:
      - SECRET_KEY=${PLAYIT_SECRET}
